homework_12
Konovalov-Konstantin/2024-03-otus-spring-Konovalov pull request #12
Opened 2024-07-10 16:42 UTC by Konovalov-Konstantin

2024-07-11 18:38 UTC, VladimirMagerov requested changes

2024-07-11 18:38 UTC, VladimirMagerov commented on hw12-Spring_Security/src/main/java/ru/otus/hw/Application.java
> +public class Application {
При создании новой книги вылетает исключение, предлагаю исправить:
![image](https://github.com/user-attachments/assets/cb443f63-baaf-43e7-8824-589bf31fe6d1)

2024-07-11 18:38 UTC, VladimirMagerov commented on hw12-Spring_Security/src/main/java/ru/otus/hw/Application.java
> +public class Application {
При редактировании комментария к книге тоже вылетает исключение, предлагаю исправить:
![image](https://github.com/user-attachments/assets/c7c114e0-090f-4461-ad94-b844b0885c56)

2024-07-11 18:38 UTC, VladimirMagerov commented on hw12-Spring_Security/src/main/resources/templates/index.html
> +<a th:href="@{main}">Аутентификация</a>
Зачем этот промежуточный этап? Почему бы сразу не отправлять пользователя на аутентификацию?

2024-07-11 18:38 UTC, VladimirMagerov commented on hw12-Spring_Security/src/main/java/ru/otus/hw/security/SecurityConfiguration.java
> +        return NoOpPasswordEncoder.getInstance();
Нельзя использовать пароли в открытом виде, их надо хэшировать. Предлагаю это сделать.

2024-07-11 18:38 UTC, VladimirMagerov commented on hw12-Spring_Security/pom.xml
> +    <artifactId>hw09-mvc-view</artifactId>
Полагаю, должно быть 12-е ДЗ

2024-07-11 18:38 UTC, VladimirMagerov commented on hw12-Spring_Security/src/main/java/ru/otus/hw/Application.java
> +public class Application {
С удалением тоже что-то не то:
![image](https://github.com/user-attachments/assets/a5b311cd-44e3-44ae-80bf-17474b588e64)

2024-07-14 17:08 UTC, Konovalov-Konstantin commented on hw12-Spring_Security/src/main/java/ru/otus/hw/Application.java
> +public class Application {
Здравствуйте, спасибо за замечание, поправил

2024-07-14 17:08 UTC, Konovalov-Konstantin commented on hw12-Spring_Security/src/main/java/ru/otus/hw/Application.java
> +public class Application {
Поправил

2024-07-14 17:09 UTC, Konovalov-Konstantin commented on hw12-Spring_Security/src/main/resources/templates/index.html
> +<a th:href="@{main}">Аутентификация</a>
Убрал лишнее

2024-07-14 17:09 UTC, Konovalov-Konstantin commented on hw12-Spring_Security/src/main/java/ru/otus/hw/security/SecurityConfiguration.java
> +        return NoOpPasswordEncoder.getInstance();
Переделал с хэшированием

2024-07-14 17:09 UTC, Konovalov-Konstantin commented on hw12-Spring_Security/pom.xml
> +    <artifactId>hw09-mvc-view</artifactId>
Поправил

2024-07-14 17:10 UTC, Konovalov-Konstantin commented on hw12-Spring_Security/src/main/java/ru/otus/hw/Application.java
> +public class Application {
Поправил

2024-07-16 18:42 UTC, VladimirMagerov approved these changes

2024-07-21 17:42 UTC, merged