homework_13
Konovalov-Konstantin/2024-03-otus-spring-Konovalov pull request #13
Opened 2024-07-21 19:04 UTC by Konovalov-Konstantin

2024-07-23 21:08 UTC, VladimirMagerov requested changes

2024-07-23 21:08 UTC, VladimirMagerov commented on hw13-Spring_Security_ACL/src/test/java/ru/otus/hw/controllers/BookControllerTest.java
> +class BookControllerTest {
Предлагаю покрыть тестами все операции от роли ADMIN и роли USER, чтобы точно убедиться, что ADMIN может делать всё, а USER - только просматривать, с позитивными и негативными кейсами.

2024-07-24 17:37 UTC, Konovalov-Konstantin commented on hw13-Spring_Security_ACL/src/test/java/ru/otus/hw/controllers/BookControllerTest.java
> +class BookControllerTest {
Добавил тестов на обе роли

2024-07-26 16:58 UTC, VladimirMagerov approved these changes

2024-07-27 15:25 UTC, merged